### ISSUE TITLE
Units?

### ISSUE THREAD

**Issue by RAFbombhead** [mlcampbe/weather-forecast-io#1]
Great widget, don't know if I'm being stupid but is there a path to change units to Celsius?

**Comment by mlcampbe** [comment]
Sorry, I am just now seeing this question. It may be too late but I believe that the units is defined in the units= parameter of the curl command. In the widget I have:

curl -s 'https://api.forecast.io/forecast/#{apiKey}/#{latitude},#{longitude}?exclude=minutely,hourly,flags

So in theory you should be able to use:

curl -s 'https://api.forecast.io/forecast/#{apiKey}/#{latitude},#{longitude}?exclude=minutely,hourly,flags\&units=si

See https://darksky.net/dev/docs#/dev/docs#api-request-types for examples.
